### ISSUE TITLE
In jbuild files, "next word" motion skips over '/' characters

### ISSUE THREAD

**Issue by TyOverby** [ocaml/vim-ocaml#51]
When I have a large path, I want to be able to move around in the middle of the path with my 'word' motions.  However, when vim-ocaml is installed, an entire path is considered to be one whole word.

**Comment by TyOverby** [comment]
Commenting out this line 

```vim 
setl iskeyword+=#,?,.,/
```

in `ftplugin/jbuild.vim` doesn't fix the issue, which is surprising

**Comment by TyOverby** [comment]
It looks like this behavior can be reproduced by running "set filetype=lisp" on a plain text file, so that may be related.

**Comment by mmottl** [comment]
The `jbuild.vim` file is probably ignored, because the filetype for `jbuild` files is set to `dune`.

I have renamed `jbuild.vim` to `dune.vim` and removed the keyword settings for now.  They are probably not too helpful for efficiently navigating these kinds of files.  We can always reintroduce extra settings later if users deem it necessary.
