### ISSUE TITLE
Syntax highlighting is broken in escaped literals

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/vim-ocaml#8]
Example:

``` ocaml
Buffer.add_string buffer {|label("|}; 
```

**Comment by hcarty** [comment]
That works here, vim 7.4

**Comment by rgrinberg** [comment]
Hmm probably so. I haven't actually tested this myself. This is just a report from the mailing lists.

**Comment by Maelan** [comment]
That should have been working indeed, since [what was then the rule for quoted strings](https://github.com/rgrinberg/vim-ocaml/blob/177c3de49109695a959cfa24c16b6a6bcb7c4580/syntax/ocaml.vim#L200) did not contain `ocamlString`. And it definitely works with [the current rule](https://github.com/rgrinberg/vim-ocaml/blob/8d2b0beeb452fc10b81412202eeafaf66c170823/syntax/ocaml.vim#L167).

**Comment by copy** [comment]
Let's close this then.
