### ISSUE TITLE
coloring on attributes indicates spurious error?

### ISSUE THREAD

**Issue by c-cube** [ocaml/vim-ocaml#82]
This didn't use to be red (and I think it's valid, OCaml and ocamllsp are both fine with it).

![ocaml](https://user-images.githubusercontent.com/1274291/180235138-65ad9200-b7d2-4821-94b9-0f857b27d61b.png)

**Comment by Maelan** [comment]
Good catch. I just submitted a fix.

Note this happens because there is now a matchgroup called `ocamlTypeCatchAll` that matches anything that is not matched by a more specific rule, and this matchgroup is highlighted as an error. That is a bit aggressive, if you want, you can tune it down by unlinking that match group `:hi link ocamlTypeCatchAll NONE`).

**Comment by c-cube** [comment]
Thank you :)
